<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { UserInfoService } from '@/services/userInfoService'
import PasswordInput from '@/components/common/PasswordInput.vue'
import type { UserInfo } from '@/models/userInfo'

const userService = new UserInfoService()
const router = useRouter()

const username = ref('')
const email = ref('')
const password = ref('')
const confirmPassword = ref('')
const errorMessage = ref('')
const loading = ref(false)

const handleSignUp = async (event: Event) => {
  try {
    event.preventDefault()
    loading.value = true
    errorMessage.value = ''

    // Validierung
    if (!username.value || !email.value || !password.value) {
      errorMessage.value = 'Bitte füllen Sie alle Felder aus.'
      return
    }

    if (password.value !== confirmPassword.value) {
      errorMessage.value = 'Die Passwörter stimmen nicht überein.'
      return
    }

    // Passwortanforderungen prüfen
    const passwordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/
    if (!passwordRegex.test(password.value)) {
      errorMessage.value = 'Das Passwort muss mindestens 8 Zeichen lang sein und mindestens einen Großbuchstaben, einen Kleinbuchstaben, eine Zahl und ein Sonderzeichen enthalten.'
      return
    }

    // Benutzer erstellen
    const newUser = {
      username: username.value,
      email: email.value,
      password: password.value,
    }

    // Cast to UserInfo since the id will be generated by the server
    const createdUser = await userService.createUser(newUser as any)

    if (createdUser) {
      // Erfolgreiche Registrierung
      // Weiterleitung zur Anmeldeseite
      router.push('/login')
    } else {
      errorMessage.value = 'Bei der Registrierung ist ein Fehler aufgetreten.'
    }
  } catch (error) {
    console.error('Registrierungsfehler:', error)
    errorMessage.value =
      'Bei der Registrierung ist ein Fehler aufgetreten. Bitte versuchen Sie es später erneut.'
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div
    class="w-full bg-white rounded-lg shadow dark:border sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700 mx-auto mt-8"
  >
    <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
      <h1
        class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white"
      >
        Konto erstellen
      </h1>
      <form @submit="handleSignUp" class="space-y-4 md:space-y-6">
        <div>
          <label for="username" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
            >Benutzername</label
          >
          <input
            type="text"
            name="username"
            id="username"
            v-model="username"
            class="bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            required
          />
        </div>
        <div>
          <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
            >Ihre E-Mail</label
          >
          <input
            type="email"
            name="email"
            id="email"
            v-model="email"
            class="bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            required
          />
        </div>
        <div>
          <PasswordInput
            v-model="password"
            id="password"
            name="password"
            label="Passwort"
            :required="true"
            autocomplete="new-password"
          />
        </div>
        <div>
          <PasswordInput
            v-model="confirmPassword"
            id="confirmPassword"
            name="confirmPassword"
            label="Passwort bestätigen"
            :required="true"
            autocomplete="new-password"
          />
        </div>
        <div>
          <p v-if="errorMessage" class="text-sm text-red-600 mx-auto max-w-fit">
            {{ errorMessage }}
          </p>
        </div>
        <button
          type="submit"
          class="w-full text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800"
          :disabled="loading"
        >
          <span v-if="loading">Wird registriert...</span>
          <span v-else>Registrieren</span>
        </button>
        <p class="text-sm font-light text-gray-500 dark:text-gray-400">
          Bereits registriert?
          <router-link
            to="/login"
            class="font-medium text-primary-600 hover:underline dark:text-primary-500"
            >Anmelden</router-link
          >
        </p>
      </form>
    </div>
  </div>
</template>
